#!/usr/bin/env python3
"""Generate the deterministic 0.05 m occupancy map for rebotarm_lab.sdf."""

from pathlib import Path

RESOLUTION = 0.05
ORIGIN_X = -4.2
ORIGIN_Y = -3.2
WIDTH = 168
HEIGHT = 128
FREE = 254
OCCUPIED = 0


def mark_rectangle(grid, min_x, max_x, min_y, max_y):
    min_col = max(0, int((min_x - ORIGIN_X) / RESOLUTION))
    max_col = min(WIDTH - 1, int((max_x - ORIGIN_X) / RESOLUTION))
    min_map_row = max(0, int((min_y - ORIGIN_Y) / RESOLUTION))
    max_map_row = min(HEIGHT - 1, int((max_y - ORIGIN_Y) / RESOLUTION))
    for map_row in range(min_map_row, max_map_row + 1):
        image_row = HEIGHT - 1 - map_row
        for col in range(min_col, max_col + 1):
            grid[image_row][col] = OCCUPIED


def main():
    grid = [[FREE for _ in range(WIDTH)] for _ in range(HEIGHT)]

    # Boundary walls: centres at +/-4.0 m and +/-3.0 m, thickness 0.15 m.
    mark_rectangle(grid, -4.08, -3.92, -3.08, 3.08)
    mark_rectangle(grid, 3.92, 4.08, -3.08, 3.08)
    mark_rectangle(grid, -4.08, 4.08, -3.08, -2.92)
    mark_rectangle(grid, -4.08, 4.08, 2.92, 3.08)

    # Static storage rack and manipulation table footprints.
    mark_rectangle(grid, -3.60, -2.40, 1.20, 2.30)
    mark_rectangle(grid, 2.75, 3.25, -0.45, 0.45)

    # TurtleBot-style interior partitions with deliberate navigation doorways.
    mark_rectangle(grid, -1.36, -1.24, 0.90, 2.70)
    mark_rectangle(grid, -0.30, 1.70, 0.94, 1.06)
    mark_rectangle(grid, -2.00, 0.40, -1.66, -1.54)
    mark_rectangle(grid, 1.34, 1.46, -2.70, -0.90)

    output = Path(__file__).resolve().parents[1] / "maps" / "rebotarm_lab.pgm"
    header = f"P5\n# generated by generate_lab_map.py\n{WIDTH} {HEIGHT}\n255\n".encode()
    pixels = bytes(value for row in grid for value in row)
    output.write_bytes(header + pixels)
    print(f"generated {output} ({WIDTH}x{HEIGHT}, {RESOLUTION:.2f} m/cell)")


if __name__ == "__main__":
    main()
